<?php

namespace EcoleBundle\Repository;

/**
 * transportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class transportRepository extends \Doctrine\ORM\EntityRepository
{
}
