<?php

namespace ArbiaBundle\Repository;

/**
 * SeanceEleveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceEleveRepository extends \Doctrine\ORM\EntityRepository
{
}
