<?php

namespace ArbiaBundle\Repository;

/**
 * SeanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeanceRepository extends \Doctrine\ORM\EntityRepository
{
}
