<?php

namespace AppBundle\Repository;

/**
 * ParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParentRepository extends \Doctrine\ORM\EntityRepository
{
}
